version: '3'
services:
  app:
    container_name: app_api
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mysql-api
    networks:
      - app_api
  
  mysql-api:
    image: mysql:5.7 # why? No idea, this is what we use at Kion so why not
    container_name: mysql-api
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - app_api

volumes:
  api:
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  app_api:
    driver: bridge